### ISSUE TITLE
App Creation Error

### ISSUE THREAD

**Issue by GraniteGames** [matteodem/meteor-boilerplate#103]
Just an issue when trying to create an app within the orion cli. I get the following error upon creation

TypeError: Object #<Decompress> has no method 'decompress'

**Comment by matteodem** [comment]
```bash
➜  Projects npm update -g orion-cli
➜  Projects orion create testApp
Succesfully created your app!

    cd testApp
    meteor
```
Works here, please give me reproduction steps and information about your node version and OS.

**Comment by matteodem** [comment]
Feel free to write into this issue and I'll re-open
