### ISSUE TITLE
Not able to generate components.

### ISSUE THREAD

**Issue by lucasdiedrich** [matteodem/meteor-boilerplate#105]
Hello, first of all, this mb is really awesome, great work.

Second, i'm trying to generate one component with: `orion generate component new_component` and return s this:
> No view called: 'component' defined

If i type `orion generate` return this:
![image](https://cloud.githubusercontent.com/assets/817482/16289151/1f3bd13a-38c9-11e6-9048-e899e3473064.png)

The things is not compatible with:
![image](https://cloud.githubusercontent.com/assets/817482/16289189/5467904c-38c9-11e6-9800-c2e151e540a2.png)

**Comment by matteodem** [comment]
This is fixed in the latest version of this boilerplate
