### ISSUE TITLE
Why client repeat call ajax to server ?

### ISSUE THREAD

**Issue by voquockhanh2** [matteodem/meteor-boilerplate#106]
Hello guys,
I just started meteor, and I use this boilerplate to study. 
My problem: it looks like client (browser) auto use websocket and ajax call to server (localhost) repeatly.
Is it default of meteor or boilerplate?
Can I turn off them?
thank you,
Best Regards

![image](https://cloud.githubusercontent.com/assets/5035982/17586526/896c3870-5fec-11e6-82fa-5be83ffeb31d.png)

**Comment by matteodem** [comment]
This is part of Meteor and isn't a probem specific to this boilerplate.

**Comment by dtuyenle** [comment]
So what was the suggestion to turn this off ?

**Comment by matteodem** [comment]
I'm not sure but I probably think it has to do with the pub/sub system of Meteor.
