### ISSUE TITLE
Semantic UI update

### ISSUE THREAD

**Issue by SalviJansen** [matteodem/meteor-boilerplate#65]
Hi Matteo,

Could you consider the following change:
REMOVE nooitaf:semantic-ui-less
ADD nooitaf:semantic-ui

The "-less" version uses Semantic UI v0.19.3 whereas the other one is being actively maintained, which makes a big difference as we are currently at v1.4.1. I didn't know why my UI was acting strangely until I noticed that.

https://atmospherejs.com/nooitaf/semantic-ui
https://atmospherejs.com/nooitaf/semantic-ui-less 

Best regards and thank you for the boilerplate!

Salvi

**Comment by etamity** [comment]
+1

**Comment by matteodem** [comment]
This is done, see 4eb624ecf26138b0eba7d13af7a75f72f9c98454
