### ISSUE TITLE
console tool doesnt work

### ISSUE THREAD

**Issue by servermeta** [matteodem/meteor-boilerplate#66]
When I opened the home page I found some new documentation about the command console tool. I think you should either integrate it in orion, or better documentate it. Anyhow it doesnt work: 

```
meteor@661fceb38f13:~/ozone2$ node meteor-boilerplate change:profile

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/meteor/ozone2/meteor-boilerplate'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

```

**Comment by matteodem** [comment]
There is no "meteor-boilerplate" file anymore in this boilerplate. Use it as it is stated in the docs, after installing it with npm (also in the docs):

```bash
orion set-profile coffee
```

**Comment by servermeta** [comment]
it doesnt work, I already tried it.

**Comment by matteodem** [comment]
Please install it like documented with npm and if it still doesn't work create a ticket with reproduction steps. "It doesn't work" is not a helpful statement in any way.

**Comment by servermeta** [comment]
I quickly posted because you closed it, without changing anything to the source thus not solving the problem (for me). 

I'm on mobile I will post more details later. The thing is that setting profile doesnt change anything. .js files stays as .js files. Resetting doesn't work either, as it simply cancel everything. Regenerating stuff recreate files with .js extension. I cant seem to generate .coffee files in any way.

Is this normal? maybe changing the profile simply adds the coffeescript package, without actually creating .coffee files? 

I think you should remove the documentation if it's not relevant anymore.

**Comment by matteodem** [comment]
Yes, it doesn't replace the current files. It does however change your configuration to generate coffeescript files. But it changes your profile to generate these files for you.

See http://screencast.com/t/0nsPnDKtw.

**Comment by matteodem** [comment]
Are there still questions open here?

**Comment by matteodem** [comment]
Feel free to post here if you have
