### ISSUE TITLE
structure and namespace for multi modules?

### ISSUE THREAD

**Issue by yuomtheara** [matteodem/meteor-boilerplate#68]
I come from Laravel PHP Framework. I would like to build 2 `modules/packages` in the same project root like this:
```
.meteor
loan/
     client/
     server/
     lib/
account/
     client/
     server/
     lib/
```
how to use namespace for this structure?

**Comment by matteodem** [comment]
That looks good to me. But for bigger functionality you would create an atmosphere package or a local one under packages/*. Please have a look here: 

- http://docs.meteor.com/#/full/structuringyourapp
- https://atmospherejs.com/i/publishing

**Comment by yuomtheara** [comment]
Very thanks, but i am not sure for using `namespace`.

**Comment by matteodem** [comment]
Namespace? http://docs.meteor.com/#/full/namespacing

**Comment by matteodem** [comment]
Please open a new one if there are any further questions.
