### ISSUE TITLE
Report package for Meteor?

### ISSUE THREAD

**Issue by yuomtheara** [matteodem/meteor-boilerplate#69]
Excuse me, i would like to generate reports for my app, so have any report package for meteor such as `excel generator`?

**Comment by matteodem** [comment]
Can you please specify your question? Do you want diagrams? Visualization of data?

**Comment by yuomtheara** [comment]
I want to generate the report that export with excel file like `php excel`.

**Comment by matteodem** [comment]
What should it report? Web Report? Or Excel? https://www.npmjs.com/package/excel with https://github.com/meteorhacks/npm

**Comment by yuomtheara** [comment]
generate to excel file (dowload).
