### ISSUE TITLE
Re-structure routes file to have a name property

### ISSUE THREAD

**Issue by brandondurham** [matteodem/meteor-boilerplate#71]
Getting this message in the browser console on a clean install:

```
You called Router.url for a route named undefined but that route doesn't seem to exist. Are you sure you created it?
```

**Comment by matteodem** [comment]
Will have a look at this the next days.

**Comment by jefflau** [comment]
I'm looking at this right now, there's a template called 'atForm' in the header that isn't defined, I'm guessing it's supposed to be some kind of login form?

**Comment by matteodem** [comment]
It is, but in a package: https://github.com/meteor-useraccounts/semantic-ui/blob/master/lib/at_form.html. Let's just wait until this bug get's resolved in ms-seo. It won't break anything.

**Comment by amazingBastard** [comment]
I was able to get rid of the warning/message by assigning the default home route a name:

Router.route('/', {
  name: 'home'
}, function () {
  this.render('home');
  SEO.set({ title: Meteor.App.NAME });
});

**Comment by matteodem** [comment]
This is fixed now

**Comment by woniesong92** [comment]
This still appears in my app. How can I fix it?

**Comment by matteodem** [comment]
Have a look at the structure of the default mainRoutes: https://github.com/matteodem/meteor-boilerplate/blob/master/routes/mainRoutes.js
