### ISSUE TITLE
Layout function description

### ISSUE THREAD

**Issue by engenheiro** [matteodem/meteor-boilerplate#73]
I was analyzing your boilerplate and thought it would be interesting you explain how the issue of the functioning of layouts in the views folder. I found the concept very interesting and I ask, if you can, describe how to define the layout for a particular page or a group of pages in the BoilerPlate page.

**Comment by matteodem** [comment]
good idea, I'll write a section about it and link to the Iron-Router docs.

**Comment by matteodem** [comment]
I think that it makes more sense to actually have a look at the iron-router package, where layouts are actually used.
