### ISSUE TITLE
load users before loading fixtures

### ISSUE THREAD

**Issue by amazingBastard** [matteodem/meteor-boilerplate#74]
Is there a way to modify the loadFixtures and loadUsers so that users are always loaded first? Right now, I'm getting back a null for author and userId when I load my fixtures and users the 'boilerplate way'

I have a fixtures file inside server/fixtures that looks like this:
```
var now = moment(new Date()),
		admin = Meteor.users.find({username: 'admin'});

Fixtures.collectionName = [];

for (var i = 1; i < 11; i++) {
	Fixtures.collectionName.push({
		name: 'random data ' + i,
		userId: admin._id,
		author: admin.username,
		submitted: now
	});
}
```
I'm loading the fixtures pretty much the same way as in default boilerplate code:

```
function loadFixture(fixtures, collection) {
  var i;

  for (i = 0; i < fixtures.length; i+= 1) {
    //collection.remove({ });
    collection.insert(fixtures[i]);
  }
}


Meteor.startup(function () {
  if (CollectionName.find().count() === 0) {
    loadFixture(Fixtures['collectionName'], CollectionName);
  }
});
```
I'm loading users with the default code inside loadUsers file that's in server/startup.

Any insight would be very helpful, thank you!

**Comment by matteodem** [comment]
I'd personally use a package that does the fixture logic for you, see here https://atmospherejs.com/packages/fixture

**Comment by amazingBastard** [comment]
Hey, thanks for that. I'll check it out.
