### ISSUE TITLE
Where to define Meteor.methods?

### ISSUE THREAD

**Issue by mayurvirkar** [matteodem/meteor-boilerplate#76]
Hey,
I cannot find any pre-defined place in boilerplate to define Meteor.methods.

So i created a methods directory in server/ and defined it there.

Do we have a predefined place which i am not able to find?

thanks in advance..

**Comment by matteodem** [comment]
Yes, there is none. I will probably add a methods/* directory, if there's nothing else that comes to mind. Most of the time I add methods to the models, if they are specific to them.

**Comment by matteodem** [comment]
Adding a methods/* folder on the root directory is the best idea. Also splitting up your code into packages is even better. This should help you
