### ISSUE TITLE
issue some praise

### ISSUE THREAD

**Issue by peterennis** [matteodem/meteor-boilerplate#77]
Just testing the latest windows preview and got this positive result:

c:\ae\aembp>meteor
This project uses METEOR@1.0.3.1, which isn't available on Windows. To work
with this app on all platforms, use
meteor update --release WINDOWS-PREVIEW@0.1.7 to pin this app to the newest
Windows preview release.
c:\ae\aembp>package catalog                  |
c:\ae\aembp>meteor update --release WINDOWS-PREVIEW@0.1.7

Changes to your project's package version selections from updating the release:

accounts-base              upgraded from 1.1.3 to 1.1.4-winr.2
accounts-password          downgraded from 1.0.6 to 1.0.6-winr.6
application-configuration  removed from your project
audit-argument-checks      upgraded from 1.0.2 to 1.0.3-winr.2
autoupdate                 downgraded from 1.1.5 to 1.1.5-winr.4
base64                     upgraded from 1.0.2 to 1.0.3-winr.2
binary-heap                upgraded from 1.0.2 to 1.0.3-winr.2
blaze                      upgraded from 2.0.4 to 2.0.5-winr.3
blaze-tools                upgraded from 1.0.2 to 1.0.3-winr.2
boilerplate-generator      upgraded from 1.0.2 to 1.0.3-winr.2
browser-policy             upgraded from 1.0.3 to 1.0.4-winr.2
browser-policy-common      upgraded from 1.0.2 to 1.0.3-winr.2
browser-policy-content     upgraded from 1.0.3 to 1.0.4-winr.2
browser-policy-framing     upgraded from 1.0.3 to 1.0.4-winr.2
callback-hook              upgraded from 1.0.2 to 1.0.3-winr.2
check                      downgraded from 1.0.4 to 1.0.4-win.0
coffeescript               upgraded from 1.0.5 to 1.0.6-winr.2
ddp                        downgraded from 1.0.14 to 1.0.14-winr.5
deps                       upgraded from 1.0.6 to 1.0.7-winr.2
ejson                      upgraded from 1.0.5 to 1.0.6-winr.2
email                      upgraded from 1.0.5 to 1.0.6-winr.3
fastclick                  upgraded from 1.0.2 to 1.0.3-winr.2
follower-livedata          removed from your project
geojson-utils              upgraded from 1.0.2 to 1.0.3-winr.2
html-tools                 downgraded from 1.0.3 to 1.0.3-winr.3
htmljs                     upgraded from 1.0.3 to 1.0.4-winr.2
http                       downgraded from 1.0.10 to 1.0.10-winr.5
id-map                     upgraded from 1.0.2 to 1.0.3-winr.2
jquery                     downgraded from 1.11.3 to 1.11.3-winr.2_1
json                       upgraded from 1.0.2 to 1.0.3-winr.2
launch-screen              downgraded from 1.0.1 to 1.0.1-winr.3
less                       upgraded from 1.0.12 to 1.0.13-winr.3
livedata                   upgraded from 1.0.12 to 1.0.13-winr.2
localstorage               upgraded from 1.0.2 to 1.0.3-winr.2
logging                    downgraded from 1.0.6 to 1.0.6-winr.2
meteor                     upgraded from 1.1.4 to 1.1.5-winr.5
meteor-platform            downgraded from 1.2.1 to 1.2.1-winr.3
minifiers                  upgraded from 1.1.3 to 1.1.4-winr.4
minimongo                  upgraded from 1.0.6 to 1.0.7-winr.3
mobile-status-bar          upgraded from 1.0.2 to 1.0.3-winr.2
mongo                      upgraded from 1.0.11 to 1.0.12-winr.4
npm-bcrypt                 upgraded from 0.7.7 to 0.7.8-winr.3
observe-sequence           upgraded from 1.0.4 to 1.0.5-winr.2
ordered-dict               upgraded from 1.0.2 to 1.0.3-winr.2
random                     upgraded from 1.0.2 to 1.0.3-winr.2
reactive-dict              upgraded from 1.0.5 to 1.0.6-winr.2
reactive-var               upgraded from 1.0.4 to 1.0.5-winr.2
reload                     upgraded from 1.1.2 to 1.1.3-winr.3
retry                      upgraded from 1.0.2 to 1.0.3-winr.2
routepolicy                downgraded from 1.0.4 to 1.0.4-winr.4
service-configuration      upgraded from 1.0.3 to 1.0.4-winr.2
session                    upgraded from 1.0.5 to 1.0.6-winr.2
sha                        upgraded from 1.0.2 to 1.0.3-winr.2
spacebars                  downgraded from 1.0.5 to 1.0.5-winr.5
spacebars-compiler         upgraded from 1.0.4 to 1.0.5-winr.2
srp                        upgraded from 1.0.2 to 1.0.3-winr.2
templating                 downgraded from 1.0.11 to 1.0.11-winr.6
tracker                    downgraded from 1.0.5 to 1.0.5-winr.4
ui                         upgraded from 1.0.5 to 1.0.6-winr.2
underscore                 upgraded from 1.0.2 to 1.0.3-winr.2
url                        upgraded from 1.0.3 to 1.0.4-winr.2
webapp                     downgraded from 1.1.6 to 1.1.6-winr.6
webapp-hashing             upgraded from 1.0.2 to 1.0.3-winr.2

aembp: updated to Meteor 0.1.7.
c:\ae\aembp>meteor
[[[[[ c:\ae\aembp ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/

And it works!

I will test some more but congratulations on a job well done!

**Comment by matteodem** [comment]
thanks! :) Great to see that it works. I don't see the community packages in the list though, are they also functional?
