### ISSUE TITLE
request the backup and restore tool?

### ISSUE THREAD

**Issue by yuomtheara** [matteodem/meteor-boilerplate#78]
I would like to request the backup and restore tool for sample?
Thanks...

**Comment by matteodem** [comment]
Please elaborate? What do you want to backup and restore?

**Comment by yuomtheara** [comment]
I want to create menu bar for backup and restore database.

**Comment by matteodem** [comment]
I don't understand what the relation is to the boilerplate.

**Comment by yuomtheara** [comment]
Excuse me, I want to request you to create backup and restore tools sample.

**Comment by matteodem** [comment]
oh okay, I think there is an atmosphere package for that.

**Comment by yuomtheara** [comment]
very thanks.
