### ISSUE TITLE
Sorting Collections

### ISSUE THREAD

**Issue by dlio** [matteodem/meteor-boilerplate#81]
I am having some difficulty sorting collections with sorting collections on the client.

With the vanilla meteor-boilerplate code, how would one perform a natural sort on the default Items collection?

Should be something like:  Items.find({}, {sort: {'$natural': -1}});
but I have been unable to get this to work by modifying any of the obvious client code.

I've even experimented a bit with /meteor-boilerplate/both/controllers/dashboard.js:5 to no avail.

Am I missing something with the collection-related packages used by meteor-boilerplate?
i.e.
    aldeed:collection2
    dburles:collection-helpers

Thanks in advance.

**Comment by matteodem** [comment]
Does it work?

**Comment by dlio** [comment]
I think my problems stem more from not quite understanding the orion workflow yet.
I'm still working on using orion to generate something like /items where I can view a demo collection.
No worries -- thanks for checking in.
