### ISSUE TITLE
coffee in creating a new project

### ISSUE THREAD

**Issue by ccfiel** [matteodem/meteor-boilerplate#82]
Hello,

How can I create a new project that has a coffee format not javascript.

**Comment by matteodem** [comment]
https://github.com/matteodem/meteor-boilerplate#available-profiles-cofeescript-and-es6

**Comment by ccfiel** [comment]
@matteodem I tried to used profile command but it only work after you create a new project.

so the orion set-profile will only work after the new project is created so the default javascripts in creating a new project is still js not coffee.

is there an option that in creating a new project i will specify coffee so that the default js will be coffee?

**Comment by matteodem** [comment]
You can use ```orion reset``` to remove the default code and replace it with coffeescript, if that's your current profile.

**Comment by ccfiel** [comment]
@matteodem I tried your idea but still this files still in js format in making a new app
/home/chris/Projects/JS/tinda.io/client/config/seo.js
/home/chris/Projects/JS/tinda.io/client/compatibility/default.js
/home/chris/Projects/JS/tinda.io/client/startup/default.js
/home/chris/Projects/JS/tinda.io/client/lib/constants.js
/home/chris/Projects/JS/tinda.io/client/lib/spacebarHelpers.js

the only file that change  is
/home/chris/Projects/JS/tinda.io/client/config/router.coffee

To replicate
1. orion create testing
2. cd testing
3. orion set-profile 
4. then type coffee
5. orion reset

**Comment by matteodem** [comment]
yes that's right, since those files only are configuration files. You can remove them by hand or rewrite them, if there's a need for that.

**Comment by ccfiel** [comment]
@matteodem ok thanks! :)
