### ISSUE TITLE
undefined when run orion generate view/model/ or whatever

### ISSUE THREAD

**Issue by Danjavia** [matteodem/meteor-boilerplate#83]

**Comment by matteodem** [comment]
Need OS and errors + node version

**Comment by SlashmanX** [comment]
Caused by https://github.com/matteodem/orion-cli/issues/13. I've provided a quick fix in there

**Comment by Danjavia** [comment]
Thanks for answer

**Comment by hpema** [comment]
Hi,

Im a nood regarding meteor so please excuse me.

Im getting this error still when creating models:

C:\Data\DevProjects\meteor\orionTest>orion generate model
orion | What's your model called (Mongo.Collection)? |  test
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory 'C:\Data\DevProjects\meteor\orionTest\u
ndefined\private\templates\js\model.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at C:\Users\Hemant.NTDOMAIN\AppData\Roaming\npm\node_modules\orion-cli\lib\f
ileManager.js:20:32
    at Array.forEach (native)
    at Object.FileManager.generateTemplates (C:\Users\Hemant.NTDOMAIN\AppData\Ro
aming\npm\node_modules\orion-cli\lib\fileManager.js:19:16)
    at C:\Users\Hemant.NTDOMAIN\AppData\Roaming\npm\node_modules\orion-cli\comma
nds\generate.js:88:29
    at C:\Users\Hemant.NTDOMAIN\AppData\Roaming\npm\node_modules\orion-cli\node_
modules\prompt\lib\prompt.js:316:32
    at C:\Users\Hemant.NTDOMAIN\AppData\Roaming\npm\node_modules\orion-cli\node_
modules\prompt\node_modules\utile\node_modules\async\lib\async.js:142:25
    at assembler (C:\Users\Hemant.NTDOMAIN\AppData\Roaming\npm\node_modules\orio
n-cli\node_modules\prompt\lib\prompt.js:313:9)
-----------

OS: Windows 8.1

awaiting your feedback...Thanks
