### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by chovy** [matteodem/meteor-boilerplate#84]
Can you provide more examples of using the generators?

**Comment by daveeel** [comment]
Take a look at this example project & tutorial: https://github.com/mcknightg/flutterbum
Not from the latest boilerplate version though. May need to purchase the tutorial videos for real understanding.

**Comment by matteodem** [comment]
Do you want to have a list of all commands? Because that's viewable here: http://boilerplate.meteor.com/
