### ISSUE TITLE
coffeescript routes not working

### ISSUE THREAD

**Issue by aacase** [matteodem/meteor-boilerplate#86]
Routes generated with the coffeescript profile don't work.

running orion generate routes while in the coffeescript profile creates the following:

```coffeescript
Router.route '/slack', ->
  this.render 'slack'
```

When routing to localhost:3000/slack i get an error that the route doesn't exist.

**Comment by jsam** [comment]
Adding coffeescript to your meteor project will fix your problem.

    meteor add coffeescript

**Comment by matteodem** [comment]
will be fixed with https://github.com/matteodem/orion-cli/issues/2

**Comment by matteodem** [comment]
Calling `set-profile` now automatically installs `coffeescript` (needs update on orion-cli).
