### ISSUE TITLE
Meteor Windows error

### ISSUE THREAD

**Issue by sonicviz** [matteodem/meteor-boilerplate#90]
Hi,
I'm just checkout out some of the various boilerplate approaches to meteor and wanted to test this (on windows). It looks really useful, especially the semantic UI use.

I cloned the git, but when I run meteor I get the following error straight away.

G:\Meteor Projects\meteor-boilerplate>meteor
[[[[[ ~\G\Meteor Projects\meteor-boilerplate ]]]]]

=> Started proxy.
=> Started MongoDB.

C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
SyntaxError: Unexpected token

G:\Meteor Projects\meteor-boilerplate>

Any clues?

**Comment by matteodem** [comment]
It looks like you solved the error in the other issue, what was the solution to this?

**Comment by sonicviz** [comment]
I just found it thanks to help from laverdet at https://github.com/laverdet/node-fibers/issues/235

Issue was corrupted os.json file in softwarerero_accounts-t9n meteor base package so I resolved it by deleting it and on new build it re-downloaded a new one that was ok.

Still unsure why it was corrupt or why the problem only occurs on with github repos I cloned.
