### ISSUE TITLE
Update to Flow-router

### ISSUE THREAD

**Issue by skolade** [matteodem/meteor-boilerplate#91]
Will this package be updated to have Flow-router implemented? I notice the Iron-route is not be maintained as it was before!

**Comment by matteodem** [comment]
What are the main reasons to support flow-router? I noticed people shifting towards it but not really know the reasons for that.

**Comment by skolade** [comment]
It as for much more control that that of iron router.

**Comment by floydnoel** [comment]
I think switching to router-layer would make more sense than switching to flow-router. This would allow users to choose whichever router they prefer. https://github.com/nicolaslopezj/meteor-router-layer

**Comment by skolade** [comment]
@floydnoel I do agree.

**Comment by stunjiturner** [comment]
i am trying to use flow-router now without much success. any how to's to wire up the boilerplate with flow router

**Comment by matteodem** [comment]
I don't think that the boilerplate has any code that prevents you from doing that. You should remove the `iron:router` package before though.
