### ISSUE TITLE
normalize not functioning properly?

### ISSUE THREAD

**Issue by blackbetty** [matteodem/meteor-boilerplate#95]
I see that there is a normalize.css file in the directory structure, but I am still experiencing some non-normalized behavior.  Is this FAD? Or do you suggest any additional normalize package from atmosphere?

**Comment by matteodem** [comment]
Normalize.css should be automatically included since it's in the client folder. What problems are you experiencing?

**Comment by OffWhite-Russian** [comment]
I'm still seeing default behavior of padding: 40px; on <ol> elements

On Mon, Nov 16, 2015 at 4:02 AM, Matteo De Micheli <notifications@github.com

**Comment by matteodem** [comment]
I removed normalize from the boilerplate as I think it's not needed anymore
